### PR TITLE
[WIP]viewの整理

### PR DESCRIPTION
**Pull request by bunbun88**
# WHAT
不要なviewの削除
部分テンプレート化

# WHY
viewファイルを整理するため

### CODE REVIEW

**Comment by bunbun88** [comment]
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxITEhUSExMVFRUXGBUXGBcXFxUYFRgXFRcXFxcXGBUYHSggGBolGxcVIjEhJSkrLi4uFx8zODMtNygtLisBCgoKDg0OGxAQGi0lHx8tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0rLS0tLS0tLS0rLS0tLS0tLS0tLS0tLf/AABEIAPMA0AMBIgACEQEDEQH/xAAbAAACAwEBAQAAAAAAAAAAAAAEBQIDBgEAB//EADoQAAEDAwIEAwcDAwMEAwAAAAEAAhEDBCExQQUSUWFxgZEGEyKhscHwMtHhFFLxI0JiFRaS0gcksv/EABoBAAIDAQEAAAAAAAAAAAAAAAIDAAEEBQb/xAAnEQACAgICAQMEAwEAAAAAAAAAAQIRAyESMQQTQVEiMmFxI0KBFP/aAAwDAQACEQMRAD8Aw64V5eXOPVHCuLpV1vaVHiWNJHXAb/5OICsFyS7KF5EOs3AxzU56c7frp81F1pUieRxHUDmHyV0xaywfTBivLwK6oEeC8FxdChZ4qPMRkY8FMqBCiKZBxUCpOC45WAyK8ukLysEiVFSKiQoUcXFIhRKsE4vLy4VCjhVb1YVW5WgJFLl1q65iiEQpIfry4r7JhLxH6hJGJGATnokI6U5cU2SJNLaX7kgENkaDv3wp2lCtdPLARIaSC8uAgECMTnOiuZaCJPkcGev5Ca+zNANrY/sd16t8lohFXRyIt5si5e5lOJWLqNQ03uaS2NAYyAQAY6FVWrnsIdTkR0O/WNFseM8NDqz6jhDcfERIw0D+EI3h4nla3EanCJicsFGbS9mLRxTnI981pO5OZ6HAlvkrLmxYcsPL2MkdoPRW1+Fc36fi8NPVT4NaONRtMzE/Iaj0SZx+B+DJNOkyrh/s/Wq5gNbpzOJ84ESYKPqex9SPhqMJ6EOHzz9E/wCKVnNAazHWNQNgOn8IBznB0tc6RG5zvEb6hSTxxfFnRnljB0zJ3lm+k7kqNg48CDuDuMKttOegwtRx2v78MHu4g4dOcgyI6aHyCTNY0GD5/YoXxvTEZfJrUdnOGcBqV2F7CwAEt+IkZABnAPVFf9n3H99L1f8A+q5QqPayKT3ME55XRJ6/JOvZh9Qufzvc7AgOJMHfVMhwboZizxyNRrYl/wCzbj++l/5P/wDXxSni3DXW7gx5aSRPwzHzAWq4lXq8zwKj2/FiCRH8apfeW7qlVpd8RDRrnUw2e2ST4IJTj0ipZYXSQgZZmOZ2BEmemNvNv/kAm1L2UrOpioCz4mhwBLg6CJgjl/VtE+avuaQDjOGgjPUgfCO+5j/ktXZ1wKVGccwY3zLcfMAeaLDU3sLC1Nuz5xb8Kq1P0t83EAfNED2eqSG+8pSYES85OAMN6pp7RNrtqvpsJax0OESJDhmSIOoIidl72T4RU9/z1CeWmCQMj4nYbj1PkEUYO6Zk9Scsvpr5Arz2SrU2l7n0oEbv3Mf290muLKowc7m/Bj4wQ5udMjTQ6xovoPtLV57RzhMFzYI6CoIPoJWVs799PMtLd+YCCO8AlXOKT0H5M/TmkuqM/K5C0HGeF0zTNxRBbEc7NoMDnYDnlkiR3nRZ+EJIzUlaOQoEKwtPRRLT0ULY4VtrX5HtdEwc+Bwc7GJVS8km9q1RpqFJoqNEYOQQJwRIIKe2doGu542ifss1wG+B/wBN8S0fBtzQZLSfDIxstBw28538uIAJIGo01wn45W0cuGJwzpfkH43Wh7WzgGSNj0/fyRFnbtrGGjlZufz6qN5wlz6hfzgAxA5TiABrKK/pXgENfyzg426DOEThKw8njZHJtL3A76o1uKY+EHPUwhbQAXLC04cD4SQf5RtyW+75RvIP54j5oays4+Iag+hGQkSycWKxLjJP4Db6kS/G4HylSoU2DUZmBr+aIsjmHQ/RUi2M69/NW8cufOKtM2yhLnyirTKr22Zygho1Hpv8lnOIWOA4DJOfD8lauu0QAfzCAr0Z+aDPJKehXkRXPQioU8R6aZxOfNO+BOBLzvifsghZGSi+AUoc50zIH1KrDK8iK8eNZESu6YdzjGuPGSgqtHl+PpPyBA+ZPqi7hwD3bmSSPNda0nB1wAkzf1MXL7mJbunAmST+/wBBCc16M2tITyx7og9C2CFC6so6ba9EVVpTbsHZn01T/GlqX6HY/tl+jnF6IcxryP06+B19DHzV1JnLSgua1zgYdpsY8TAVXCxLXU3ZGnkRkSkntPxBxrik3/YAZ/5HOnYcvqVq5a5Fya4+t7tV/o1vbI/0gpAAwG48HA7LOv4ZGwxk8uXDprpv6LVNuCLdrwMw35kT9V23c3Li0cwiIjaMkkHb6qp9ozeX3H9IzPCLX/V5T/vDmkO+KWkGZP8AG2qaU/ZVn9qa8KtzUrmoQAG+GSRsfNaWnTZuuP5mdqfGLKwJqJix7L0/7VL/ALYp/wBo9F9Dt/dAbIS4dT2hZXknX3DbZ8OXl5eXZOida4gyCQRkEahaS3uvfM5geV4w8DEn+4Z33WaK7Se4GWyD9eytOhOfGpxNHb20STUcZ0+IrTW7WBjRJnMTusrwa85/hcAHaEE4PcBOalQcsaRt+aI3NV2cz6rOkEzOmNtD3/NkbRpwPTv1QtvU1kbRH0Kk+7DWwMyMeWM9FmbsYV3d4OeB/tEHr5K4XXM0ka8oMfWF884x7QVKby0aznp4Jr7Pce96YIhwz4+ab6UqsX61OkbC2k4OxHoFe+JQVk4uEjr+BEuBIA758Fmehy2CXLSS7PbyQ9uyII0gnXomTaW5Hb1VTqPwkaY80GwgW0ZOd3HfpMq6vU5XTj4ft/hC1KxpuBidvMrN8R9o2tqFhmZgnOPJPhBy2hM509m1FVr2h/XHpqgi0F2ScnTaBoEq4NfAy2cajWO6btn9QaO3n0U+1l3rRG8Bn4Z3BIxtjCzjnH3zZEmQPNaag+JnM+gSupwwvqEyDmR4D6JsZaAd9FlGmWHBJadWkyPJNbCyNQ4loAyYz4AqPCOHl7iOgycHy7GFpqdENAaNBgLJ5Pl+mqXYUMfPbKqFMNaGjQeqkVMhRhcZtt2zUlRGVyV0qLgqLPka8vLhK9KbDvMrLWrJiM7HZVBskDqmNC2gCG5Gupnv2VmTyZ6pB1owOEloBESmtLTOkR3VFv8ApwMx+eKLpj4dAD3SZGVMg44jQ7FB3NwKbHPOoEzvPRHVqMxAz8kPdWYcxzDGQhi9ka0fKb24dUeXOJMndOeBMZTu4ZU94wFwa8NLQ8deR2RnYpnS9jwXy7Q6CYHqnVp7P0ab5DRIGxP1W95Y8aMaxS5Gh4dT+GRqf3TBlLKp4fgDojnNA+oWBo2opLMk/mFSGSUW4H1Q5EY3KGiCD2hPK0unQH1XzDilpy8lT31N7qnMS1rialPlIH+piATMiCcDML6zxW3Dmx9lj7n2TplnM2ebO62ePOMU7M2eDb0c9jbkPp+7P6wZB7LX21eW5EEfh81m/Zngz6TiYjuSCtKKETJyUnM1y0NxJ8dlNR8nufyMKp91yaycxrgeQyiPdNH27pVf64B9I06dktBs1vAOJNe3l0I2jROcL5TYX3u6wdkg4IBif2819Psq0tByPT7Ll+ZhcJX8jccrQRCgWq2FwhYxhQQoEIhzVAhEQ+NheDCVFEWIPNiPDr4dfLK9KaZOkG2lGMFuu+EzpUxIEdl5lMFsxtnr4FVUpJgH1+SFO0czI7Yxp0+UxqO8SPApiGNLUutnf3HPhATGjQ1AOvXYoGrIiFF/mB4Suiq0nr4jVedTz0P1XH0Zg7/m6WMLHtBEAfx4Iemwtw7yPXsUQWnBaT4FC16x0IPQ9PJHG2C6Qxs3DTujXOMjdJKT4dIRbLuAeqJxoiTYyfVAGdkE+HOnsq3VCW90HSqHzUaL40XVXgSAJxCBaw8x76/wrX7nXdRpudOA1sZzk+iFrQPuE0qLQI0J9fko1G9z49vBdFIuMknyGPkuPp/7fl1S7CPNc2NR5DISjioGBJ8xj5p7QtobMfIABKrloJMAb5mfqjiqAbMxVo8zv1aZgQPotvwLijS0AmSNZIWVuKAHeT4DxwiOHgtMxj83Q+RjWSJMbpn0ShcgokLPcOucBPLd8riThTNJaQoFqtXCEBZ8TZTJwAT4J1w/hTh8Th8lseG+zrKY0V/E6Qa2NF2f+vnLjELJl1ozVKnEzoceHY/yqHEMd2J+fnhNDQaDOJ+qHr0Njp0/yta0YW7ZENxLfr9kztXggEEyO2vklFIObPLEb7DxCLsrsg5AI6qixoRzZ6fm6qrEmBknsEW0NdDpBUuTmwweegU4Xsin8gPOYwI9SqatA6nfojatvy45pPTQeitZRBEEnt0CNRK5bFBELtHJV95QI+yAoXIZgyqUdmiLVDIvxohaojK4L1mmypqXJeYDcI5RtBWXNpA91F1t3idExtLUkZED5q27pNIiMJaiZpyVgFNj2iJV1Gg45Oe2hXW2rm5Bkd8/NFGu3fmBjUfYoOBHMjUuWtBkuDuhAj5BKq9WT+yLqBpIJBnr+4QZpT+kxnw8oRA/kCNEzv5/ZT9wdx02TBlu4ZJ/ZV1bZxyZ85PzKjjopS2F8Op6J/atSvhlPATui2Fwsz+o2osC4QpQvJARLkSLj7tAMpu+qlfEnSNJWjx3U0BJaFVOniD+eKqqWhbnm5h0xHhOv2XeQHX6CfREW7TOOb9vEr0MdoxSVMWck64jbb1UyxoE7/M+Sb/0oOoyesYU/wDpzW6RPl9lXAimLaDDrOu2w8uqYM5tAY89FIWw8+37BT/poGo9PuiiqBkyirULREeJ79yo23EGTB8PNSeDEbJXcWRfPLrtG0oqIh9Uphw+E4Su5sjMcuPukbeK3FCdf1coB6IG69ta+7QDnXboVaQxckP/APp0PiDoMdEztbIzpy9F8yp+0lyKpqc5zAM6R4LSU/ai4dynlgEwe46q6ZbcmbypVp0mkuPTXb+EsqXgcTGgPTI/cJHa16rwHVCXNyCDoQUyot5YgSdD3G3yQ0JYY17jgYCtqcNGDqfMfJdbSc2MYOW/cK63pg5nyzIVcCuQvqUjoY6YmQpMt+mU6daOOYHqRI9UDVby6N8ZIB9YVcEic2wKqOXoPT90FdNPWemcjyTOqxoGR8/odkpuX8s9NiUM+i49jzgeWidU6aFnuFgwHA4T63MhcPy8LjLl8m7HNNFwC4QrGU3HQLzqRGoWOmMtCxxQN6/CNcUs4g8RlPxfcRix1TP0AgBF29Zw6eMxH7oQOBGNevbx2UaLnAwAT0C7sHqzLJKx1TO5Mnt9JhWU+bHwg+B085VdnSc4fFgdAmLKEDoE5SYhxQIyg4mZj6r1SRIB5t4/lE1HNA3nXf1KpDR0gbouQNHKlL4cjTfbOiCawtOOxI7IqrWOczoI2xuqHVObGpjy8ESaKpnrmxp1GktbJHnlZziPA2VQWho5gMLS21U09fTuqLqiKhlpyr0Nxyoxdv7NEO5Swaic9c7rUWXDGOdAAgfbopvt6jj8R8ydtEdbQ0crPicdeipsZOWtEL9jIFIADHmI81Jlmdp0E/ZH2XC2g8ziS47bx3PomdvRboNuuqhmYvtrA8uv/JpP8qVVpGW8v87FH1qDp9OkKh9kQTGPoqbZEkBvg/qE9gB9xgoesxrRgEDxH0JTN1i8jJQ7+HuGfUHQpb5MJcUZu5quDsOx0gT/AIVDG8x/SR6we4TDiFp8Wh1/CCrW2sbIVGwnIvsRDY2THh9yAYVFuwcsIWm4tfkY6pPmQvGFhf1GstrxoXq921yX0GyFN9NcTnKqNfBXYtKW8Qp4TByDvZhSHYYipCCUzsraT9dUHZD4j1Tu3Ib+Z9F3PG2jLm7GljS008Ud7sIK3qwBOp21PoiQZPRbl0ZGRfQBJMBRrWuBsrDrrleqvn79VKLQrr0gIgTBQzHt5oAEjvk7nHSOyc1GgAuKzrGc9dhiDztM40LsjzGELGxjYzbDsFvb8CHueETlnonX/T8qdBkGIjyVtCjNUrB26JtaYB5WgE7k6DyGqe3NGVRSogbfsokXZUymZgTnf80Vn9HmZg7kfRXco/wvOEiNO6spGa4qz/7JcfigNa3sIDv/ANSZWko3TXQ776LO3ldpqvAOmJ8k14bWbyAYJydpCBdjsi+lDLn6AeZP0QVRxnHy/bcKw1vEeGqpq1JMQfE/ZExABd0Pi5vvn+V3l2CteydD+eC45hQUWdojZDXVAjMo2hT3O6GuxncIciuNBRdMOsHYCLqFLuHuxGqOqLzuSNNo6EXYqQ9zoiFXUCWuwhLQbDyUe3WdEJX+F0oznxOi7PiytGfKhnagxr5nU94RtIeJP56JZYu6GTud/mnFPSF0omJkAwHb1JUm0hMrriFW65gIi0zlwHBrgSIgwdDos7TugxzHf8h9UbxC/NQ8g0GvdBC3BOYQMfjTrZsQcTKg54lKLSsGDMx6wmlrWBI3GyKxMotEq9T1OFSP4CurEE47n0UGkbn/AAoCcDzsPVA8Ze4NHnMfRGucPz9llvay/dTdTIMtlxd30wqk9Bw3I57phzGd0PcVSxwLJB6oayvzWM02kD+46DsOqdC3x1xqgTNMkkN+GXQqNBMToUTcUwRp6E/RZ7g1SOcf8vsmjrjCJSMko7KeXMek/wAqxvoUO2rzHr8oU2T1QkotpkhRew6q63aSrqggKNaID2JCLruQNNwnBRBcuB5MamzdjeheoPUpUSsw4U8RaiKbpb9AquJfpKC4VczLSV0fEkKyK0O7CvBz+fsmH9b5lZ25qchHRFWlyCTMeGuNfzxXUhMySgOW1MST4BUXLnddtB3Qv9ShX3uoONimcilE9YvDi78KLbQOoyhGUIdNM5EHGvpujG3j2CS3HVSx6fwWGoQIx0IKrqcSbTA2GyGvOK0znASPiN7zgtaZ+RjBhDYE0aWjxzLo1IA9Uay9DjOADv2WDtKpDjzeXfSE9o3Ih3XAH3+Suxbih1c3YAwcn88kk45TD6YB23+qsFYQcZ/ZA3FzHw7EfMqmwoqiuzuSxzaVMNLYnvJTdz6r2xMbY19VnPdBruduoUqnEan9xHYJXIddo0Nk9rfhB657qy4u4zIj7rO21zynXMjPiPsUawl57EzHQolIU47GlpUJMxhM6YyhbS3DQMo+1oyZRoWw62ZAyo3T8K84CGuHgiET6BFYcJwig5LC8h8JiwrgeVubN2PoFXCF2VRUr7LMot9DgW/GCsjdXPunk+nnham8qACSsf7Q03QXkQNguh40GnsXN6NPSuG1mYiRE+aBrFzJA1kLJcC4uaRIGkfdbFtZtWnzBbpLiITsrp37gDOx+2FI3AcDOh+o0QVZnRQnB/NAFSkFQWy8c0y0kEd11/G6g3mUvbUiZQlaoNPzsUabJQReX/OZgTmSMT5Jrwe25oJ0xKztu3MLW8FEDxTIdi8mi+vYNnCq/TE6/JPWUgc9pVFSzDgU1oVFiuPTVA16cT44Tg2jmyOqiyiCCD4eiU0GmZ8uUWaef2Rd5SHMYVNOjJS6GpnbWgST3Whsrbl+Sos6UD0TixtS7VHFC5Mnb0S5OrWhAVNCmNEYcBNSFNldV0YSm9q8vgj6z4BlKbuX/CP8JeWairZcFbAKVaXGUxY8nAHnsvWXDQ3WSepTFlKF5/NlUpNo3RiZ25ueXZK6xqPMgQE/4hytaS+FRwKpzfEf07LZjioIpysr4VwnIfVOBsVlP/kK7bhg1OgW14ndPIIY0wOiyT+Ce8re9fnsVoxvdsXLbPnZpPGYK0HAuIEDldgaBPvaDhjGskQPBYp1KrOGnC0xksiK9PgbEu3Vbs6dSUutbwxDtUwtHBxhK4NBFFx1Qjwm1elIQTqOUSJZ60ZJC1fDWHlSLhtqSZWlt2cvgnREZGEsrExHSCmFGISpj8wmVHRMQoL5Qdkp4hbxJHgmNKrGAqrkyQO6jLWjOG0PRX2vDynlKiDEgI1lFoBPkh4BcxfaWEa7ppaMjC6BgAbqby1jZcQP3V6WyrbLqbYVd3XA1PkNShn3T3/oHKOp18gpUrYDJyep19Vgz+fCGobY2GBvbK38z+w6b+ZV1KgArQFILj5c88juTNUYqPRwBdXYXkkIQXfs++q2Xkx4wu0KPuwGAg9gjXPqOEVKgYPFKKvFG0XfDFRw/wBxXc4fJms1tqxoYJAB6JB7VkPpxSIa7ss3xT2pqVTytMHo1E8PpHlHNJccmStUaloFQdg1vZy0c55nd0PWtZ2wnJo9Epvb5rHBkyZTVFIaLa3CJ0CV3FpWp5AMDday4ufdt2k6Sk/ELmsWOYOWNzuqk0hbb9hLb8XdEEK0cSbvvoUpFpVy5gJjVXCm6pTMMJPYaIXRNmm4XxSmBAjWcdTqn9O7a9uHCVieHey1U05bIcRoTC63gF5TOHTPQzCtSitWKaZsH1tCCim8QAjKz1paXVMf6rSWu37qmsKgMkGNlfNE4M1B4jpGqLpVxAkrCP4oGmJg7o8caacBw2V8inE1zLmSYKYU6kgD1Wf4YxzgC0eafUbMn9R8tlnzeZDH+WHHC5FguTowT3Og/dTp2xJl55j3+wRFOiBsrYXHz+ZPL30aYY4xINYF5xI8FOF1ZbGnIXl5dVFHFwrq4ZUIZJ/xCTkyUl4xhuMLi8ux/YWuj3AqDeXmjPVNLZx5j4Lq8nYX/IwGGM/SlN/aMPxFonqvLyfm9iIVcRM8oKJtqTfduxsvLyGfZPYnaUWi3kASdSpcPpCYjC8vKmC+jQW1qyP0/VH2VBozC8vIJFI9eD4Ssf7R13NpmDHovLyGPYS6MhUpNNHmIz1Tb2Ds6dSo4vaHFsRM48tF5eT5v+ORXuj6nb0wBgIpoXl5een2aSwKbV5eQFHSqyF5eUIji4V5eVlniuri8oiH/9k=

**Comment by tomohironagano** [comment]
nice render! LGTM!

**Comment by bunbun88** [comment]
image

**Comment by kenta-matsuzaki** [comment]
LGTM

**Pull request merged**
